stages:
    - deploy
    
deploy:
  stage: deploy
  script:
    # - |
    #   if pgrep -f 'python main.py' > /dev/null; then
    #     pkill -f 'python main.py'
    #   fi
    - rsync -avz --delete ./ user@10.0.6.78:/home/user/spitec
    # - poetry install
    # - nohup poetry run python main.py >/dev/null 2>&1 &
    # - exit 0
  only:
    - main