stages:
    - deploy
    
deploy:
  stage: deploy
  script:
    - git pull origin main
    - |
      if pgrep -f 'python main.py' > /dev/null; then
        pkill -f 'python main.py'
      fi
    - poetry install
    - nohup poetry run python main.py >/dev/null 2>&1 &
    - exit 0
  only:
    - main