stages:
    - deploy
    
deploy:
  stage: deploy
  script:
    - |
      if pgrep -f 'python main.py' > /dev/null; then
        pkill -f 'python main.py'
      fi
    - cd ./spitec && poetry install
    - poetry run python main.py &
  only:
    - main