stages:
    - deploy
    
deploy:
  stage: deploy
  tags:
    - spitec
  script:
    - source ~/.bashrc
    - /home/gitlab-runner/.local/bin/poetry --version
    - /home/gitlab-runner/.local/bin/poetry install
    