name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # Step to stop the running application
      - name: Stop Application
        run: |
          if [ -f "/tmp/gunicorn.pid" ]; then
            kill -9 $(cat /tmp/gunicorn.pid) || true
            rm /tmp/gunicorn.pid
          fi
          # Stop any existing pm2 processes
          npm install -g pm2 || true
          pm2 delete all || true

      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Specify your Python version

      # Install Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      # Install dependencies
      - name: Install Dependencies
        run: |
          poetry install

      # Install Node.js for pm2
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Use a stable Node.js version

      # Install pm2 globally
      - name: Install PM2
        run: |
          npm install -g pm2

      # Start the application with pm2
      - name: Start Application
        run: |
          if [ ! -d "./logging" ]; then
            mkdir logging
          fi
          # Start Gunicorn with pm2, saving the process list
          pm2 start --name gunicorn "poetry run gunicorn -w 4 -b 0.0.0.0:80 --pid /tmp/gunicorn.pid main:server" --output ./logging/log.txt --error ./logging/log.txt
          pm2 save
          # Wait for PID file to confirm application start
          COUNTER=0
          while [ ! -f /tmp/gunicorn.pid ]; do
            if [ $COUNTER -ge 15 ]; then
              exit 1
            fi
            sleep 1
            COUNTER=$((COUNTER+1))
          done
          sleep 10

      # Archive logs as artifacts
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: application-logs
          path: ./logging/log.txt
          retention-days: 7
